services:
  mq:
    image: rabbitmq:3.9.26-management-alpine
    ports:
      - '5672:5672'
      # for rabbitmq-ui in browser
      # default user/password is guest/guest
      - '15672:15672'
    restart: always
    container_name: rabbit-mq-net-core
